force-app/main/default/objects/Activity_Assignment__c/Activity_Assignment__c.object-meta.xml
<CustomObject>
    <label>Activity Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Activity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Activity Assignments</relationshipLabel>
    <relationshipName>Activity_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Assignment__c/fields/Onboarding_Activity__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Activity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onboarding Activity</label>
    <referenceTo>Onboarding_Activity__c</referenceTo>
    <relationshipLabel>Activity Assignments</relationshipLabel>
    <relationshipName>Onboarding_Activity_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>Specialization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/Onboarding_Activity__c.object-meta.xml
<CustomObject>
    <label>Onboarding Activity</label>
    <nameField>
        <label>Onboarding Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Activity__c/fields/Expected_Duration__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration__c</fullName>
    <label>Expected Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Onboarding Activities</relationshipLabel>
    <relationshipName>Onboarding_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/fields/Trailhead_Points__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_Points__c</fullName>
    <label>Trailhead Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aloha</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Org62</fullName>
            </value>
            <value>
                <fullName>Quip</fullName>
            </value>
            <value>
                <fullName>Services Org</fullName>
            </value>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Slides</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
            <value>
                <fullName>Trailblazer</fullName>
            </value>
            <value>
                <fullName>VolunteerFx</fullName>
            </value>
            <value>
                <fullName>Webassessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeeTriggerHandlerTest.cls
@isTest
public with sharing class EmployeeTriggerHandlerTest {

    /*
        Runs before each test in this class, generates test data.
    */
    @testSetup
    private static void testSetup(){
        
        // Onboardings
        List<Onboarding__c> onboardings = new List<Onboarding__c>{
            new Onboarding__c(Name = 'Technical Consultant - First 90 Days', Type__c = 'Role'),
            new Onboarding__c(Name = 'Solution Consultant - First 90 Days', Type__c = 'Role')
        };
        insert onboardings;

        // Onboarding Activities
        insert new List<Onboarding_Activity__c> {
            new Onboarding_Activity__c(Onboarding__c = onboardings[0].Id, Name = 'Culture & Benefits', Type__c = 'Session', Expected_Duration__c = 240),
            new Onboarding_Activity__c(Onboarding__c = onboardings[0].Id, Name = 'App Customization Specialist', Type__c = 'Superbadge', Expected_Duration__c = 360, Trailhead_Points__c = 4500),
            new Onboarding_Activity__c(Onboarding__c = onboardings[1].Id, Name = 'Culture & Benefits', Type__c = 'Session', Expected_Duration__c = 240)
        };

    }

    @isTest
    private static void testInsertContacts() {

        // Get onboardings, we need IDs
        List<Onboarding__c> onboardings = [SELECT Id, Name FROM Onboarding__c];

        Test.startTest();

        // Insert some contacts
        List<Contact> contacts = new List<Contact>{
            new Contact(FirstName = 'Cliff', LastName = 'Gallagher', Onboarding__c = onboardings[0].Id),
            new Contact(FirstName = 'Alejandro', LastName = 'McQuirter', Onboarding__c = null),
            new Contact(FirstName = 'Farooq', LastName = 'Moreno', Onboarding__c = onboardings[1].Id)
        };

        insert contacts;

        Test.stopTest();

        // Verify results -- select contacts with their activity assignments
        // Sort by name so order is the same as above
        Map<Id, Contact> contactMap = new Map<Id, Contact>([
            SELECT Id, FirstName, LastName,
            (SELECT Id, Onboarding_Activity__r.Onboarding__c FROM Activity_Assignments__r)
            FROM Contact
        ]);

        // Check for expected number of assignments for each contact
        System.assertEquals(2, contactMap.get(contacts[0].Id).Activity_Assignments__r.size());
        System.assertEquals(0, contactMap.get(contacts[1].Id).Activity_Assignments__r.size());
        System.assertEquals(1, contactMap.get(contacts[2].Id).Activity_Assignments__r.size());

    }

    @isTest
    private static void testInsertContactsEmpty() {

        Test.startTest();

        // Insert some contacts with no onboardings
        List<Contact> contacts = new List<Contact>{
            new Contact(FirstName = 'Cliff', LastName = 'Gallagher', Onboarding__c = null),
            new Contact(FirstName = 'Alejandro', LastName = 'McQuirter', Onboarding__c = null),
            new Contact(FirstName = 'Farooq', LastName = 'Moreno', Onboarding__c = null)
        };

        insert contacts;

        Test.stopTest();

        // Verify results -- select contacts with their activity assignments -- no assignments expected
        System.assertEquals(0, [SELECT Id FROM Activity_Assignment__c].size());

    }

}