force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
            <value>
                <fullName>Specialization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/Onboarding_Activity__c.object-meta.xml
<CustomObject>
    <label>Onboarding Activity</label>
    <nameField>
        <label>Onboarding Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Activity__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Onboarding Activities</relationshipLabel>
    <relationshipName>Onboarding_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Onboarding_Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aloha</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Org62</fullName>
            </value>
            <value>
                <fullName>Quip</fullName>
            </value>
            <value>
                <fullName>Services Org</fullName>
            </value>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Slides</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
            <value>
                <fullName>Trailblazer</fullName>
            </value>
            <value>
                <fullName>VolunteerFx</fullName>
            </value>
            <value>
                <fullName>Webassessor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandlerTest.cls
@isTest
public class TriggerHandlerTest 
{

    //Runs before each test in this class, generates test data.
    @testSetup
    private static void testSetup(){
        
        // Onboardings
        List<Onboarding__c> onboardings = new List<Onboarding__c>{
            new Onboarding__c(Name = 'Technical Consultant - First 90 Days', Type__c = 'Role')
        };
        insert onboardings;
    }
    
    //Method to test OA validation
    @isTest
    private static void testValidation()
    {
        try
        {
            List<Onboarding__c> onboardings = [SELECT Id, Name FROM Onboarding__c];
            Onboarding_Activity__c badOnboardingActivity = new Onboarding_Activity__c();
            badOnboardingActivity.Name = 'Test Bad';
            badOnboardingActivity.Onboarding__c = onboardings[0].Id;
            badOnboardingActivity.Type__c = 'Module';
            
            insert badOnboardingActivity;
        }
        catch(Exception ex)
        {
            Boolean expectedExceptionThrown =  ex.getMessage().contains(' is a Trailhead Module and requires Points > 0');
			System.AssertEquals(expectedExceptionThrown, true);
        }
    }
}